CREATE CACHED TABLE CONFIGURATIONS (
    ID INTEGER IDENTITY PRIMARY KEY,
    CONFIGURATION CLOB
);

CREATE CACHED TABLE REQUESTS (
    ID VARCHAR(50) PRIMARY KEY,
    CONFIGURATION_ID INTEGER FOREIGN KEY REFERENCES CONFIGURATIONS(ID),
    REQUEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REQUEST_URL VARCHAR(1K) NOT NULL,
    PROXY_URL VARCHAR(1K) NOT NULL,
    REQUEST_METHOD VARCHAR(10) NOT NULL,
    REQUEST_HEADERS VARCHAR(10K) NOT NULL,
    REQUEST_CONTENT BLOB
);

CREATE CACHED TABLE PROXY_REQUESTS (
    REQUEST_ID VARCHAR(50) PRIMARY KEY FOREIGN KEY REFERENCES REQUESTS(ID),
    PROXY_REQUEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROXY_REQUEST_HEADERS VARCHAR(10K) NOT NULL
)

CREATE CACHED TABLE PROXY_RESPONSES (
    REQUEST_ID VARCHAR(50) PRIMARY KEY FOREIGN KEY REFERENCES REQUESTS(ID),
    PROXY_RESPONSE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROXY_RESPONSE_STATUS_CODE INTEGER NOT NULL,
    PROXY_RESPONSE_STATUS_LINE VARCHAR(1024) NOT NULL,
    PROXY_RESPONSE_HEADERS VARCHAR(10K) NOT NULL,
    PROXY_RESPONSE_CONTENT BLOB
)

CREATE CACHED TABLE RESPONSES (
    REQUEST_ID VARCHAR(50) PRIMARY KEY FOREIGN KEY REFERENCES REQUESTS(ID),
    RESPONSE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESPONSE_HEADERS VARCHAR(10K) NOT NULL
)