CREATE CACHED TABLE CONFIGURATION (
    CONFIG_ID VARCHAR(200) PRIMARY KEY NOT NULL,
    LAST_CONFIG_USED BOOLEAN NOT NULL,
    CONFIG_PATH VARCHAR(200),
    CONFIG VARCHAR(10M) NOT NULL
);

CREATE CACHED TABLE REQUEST (
    REQUEST_ID BIGINT PRIMARY KEY,
    CONFIG_ID VARCHAR(200) FOREIGN KEY REFERENCES CONFIGURATION(CONFIG_ID),
    CACHED BOOLEAN DEFAULT FALSE,
    REQUEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REQUEST_URL VARCHAR(1K) NOT NULL,
    REQUEST_PATH VARCHAR(1K) NOT NULL,
    PROXY_URL VARCHAR(1K) NOT NULL,
    REQUEST_METHOD VARCHAR(10) NOT NULL,
    REQUEST_HEADERS VARCHAR(10K) NOT NULL,
    REQUEST_CONTENT BLOB
);

CREATE INDEX REQUEST_PATH_INDEX ON REQUEST(CONFIG_ID, REQUEST_PATH, REQUEST_METHOD);

CREATE CACHED TABLE PROXY_REQUEST (
    REQUEST_ID BIGINT PRIMARY KEY FOREIGN KEY REFERENCES REQUEST(REQUEST_ID),
    PROXY_REQUEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROXY_REQUEST_HEADERS VARCHAR(10K) NOT NULL,
    PROXY_REQUEST_CONTENT BLOB
)

CREATE CACHED TABLE PROXY_RESPONSE (
    REQUEST_ID BIGINT PRIMARY KEY FOREIGN KEY REFERENCES REQUEST(REQUEST_ID),
    PROXY_RESPONSE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PROXY_RESPONSE_STATUS_CODE INTEGER NOT NULL,
    PROXY_RESPONSE_STATUS_LINE VARCHAR(1024) NOT NULL,
    PROXY_RESPONSE_HEADERS VARCHAR(10K) NOT NULL,
    PROXY_RESPONSE_CONTENT BLOB
)

CREATE CACHED TABLE RESPONSE (
    REQUEST_ID BIGINT PRIMARY KEY FOREIGN KEY REFERENCES REQUEST(REQUEST_ID),
    RESPONSE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESPONSE_HEADERS VARCHAR(10K) NOT NULL,
    RESPONSE_CONTENT BLOB
)