---
id: default-configuration

url: "*"
autoProxy: true

logging:
  enabled: true
  httpRequestContent: true
  proxyRequestContent: true
  proxyResponseContent: true
  httpResponseContent: true

clientConfig:
  connectTimeout: -1
  connectionRequestTimeout: -1
  handleRedirects: false
  maxConnections: -1
  readTimeout: -1
  useSystemProperties: true
  
cache:
  enabled: false
  expirationTime: 0
  
listeners:
  - info.stasha.proxywarrior.listeners.LogToDbListener
  - info.stasha.proxywarrior.listeners.LogToConsoleListener
